services:
  - name: rosytunes-site
    type: web
    env: ruby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rosytunes-db
          property: connectionString
databases:
  - name: rosytunes-db
    ipAllowList: [] # only allow connections from services in this Render account
